aws:
  s3:
    mock: false

spring:
  datasource:
    url: jdbc-secretsmanager:postgresql://${RDS_HOST}:${RDS_PORT:5432}/${RDS_DB:ebdb}
    username: ${RDS_SECRET_NAME}
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
